// RiskEngine.jsx — Phase 2 rebuild screen
//
// DRAFT — PENDING PIXEL SIGN-OFF
// Phase 2 scope: Monte Carlo tab (mock data), placeholder tabs for VaR,
// Expected shortfall, Stress testing, Hedge effectiveness.
// Phase 3: swap mock data for real API calls.

import { useState } from 'react'
import Card from '../ui/Card'
import Button from '../ui/Button'
import EyebrowLabel from '../ui/EyebrowLabel'
import Icon from '../ui/Icon'
import Tabs from '../ui/Tabs'
import ThinkingIndicator from '../ui/ThinkingIndicator'
import FanChart from '../ui/charts/FanChart'

const MODULES = [
  { id: 'monte-carlo',         label: 'Monte Carlo',         live: true  },
  { id: 'var',                 label: 'VaR',                 live: false },
  { id: 'expected-shortfall',  label: 'Expected shortfall',  live: false },
  { id: 'stress-testing',      label: 'Stress testing',      live: false },
  { id: 'hedge-effectiveness', label: 'Hedge effectiveness', live: false },
]

function generateMockHistory(spot, histDays = 90) {
  const points = []
  let rate = spot - 0.030 - (Math.random() * 0.005)
  for (let day = -histDays; day <= -1; day++) {
    const drift = (spot - rate) / Math.abs(day) * 0.35
    const noise = (Math.random() - 0.48) * 0.003
    rate = Math.max(rate + drift + noise, rate * 0.995)
    points.push({ day, rate: parseFloat(rate.toFixed(5)) })
  }
  return points
}

const MOCK_HISTORY = generateMockHistory(1.0847, 90)

const MOCK_SIMULATION = {
  pair:      'EUR/USD',
  spot:       1.0847,
  budget:     1.0700,
  forwardTo:  1.0950,
  days:       90,
  histDays:   90,
  history:    MOCK_HISTORY,
  p10:        1.0612,
  p50:        1.0847,
  p90:        1.1084,
  var95:     -0.0187,
  narrative: `Your EUR/USD exposure is currently above your budget rate of 1.0700.
The simulation projects a 10% probability that spot will fall below 1.0612 over
the next 90 days, and a 10% probability it will exceed 1.1084. Your current hedge
cover of 68% reduces the portfolio's downside exposure materially — the unhedged
portion carries the majority of the rate risk shown in the distribution below.
Your policy target of 75% cover, if met, would reduce the unhedged tail by a
further 23% of the open notional.`,
}

function AIDisclosure() {
  return (
    <div style={{
      padding: '8px 12px',
      background: 'rgba(141,164,196,0.10)',
      borderRadius: 'var(--radius-2)',
      borderLeft: '3px solid var(--snh-slate)',
      fontSize: 'var(--fs-eyebrow)',
      color: 'var(--fg-3)',
      marginTop: 16,
    }}>
      AI-generated decision support —{' '}
      <a href="/legal" style={{ color: 'var(--snh-gold)', textDecoration: 'underline', fontWeight: 'var(--fw-bold)' }}>
        full disclosure.
      </a>
      {' '}Generated by Sumnohow's AI risk engine. This is decision support, not regulated
      investment advice. Validate against your own assessment before action.
    </div>
  )
}

function MonteCarlo() {
  const sim = MOCK_SIMULATION

  return (
    <>
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 16 }}>
        <Card>
          <EyebrowLabel style={{ marginBottom: 8 }}>Spot rate</EyebrowLabel>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28, color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums' }}>
            {sim.spot.toFixed(4)}
          </div>
          <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>{sim.pair} · live</div>
        </Card>
        <Card>
          <EyebrowLabel style={{ marginBottom: 8 }}>Budget rate</EyebrowLabel>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28, color: 'var(--snh-gold)', fontVariantNumeric: 'tabular-nums' }}>
            {sim.budget.toFixed(4)}
          </div>
          <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>Planning benchmark</div>
        </Card>
        <Card>
          <EyebrowLabel style={{ marginBottom: 8 }}>P10 / P90 range</EyebrowLabel>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28, color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums' }}>
            {sim.p10.toFixed(4)}
          </div>
          <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>to {sim.p90.toFixed(4)} · 90-day horizon</div>
        </Card>
        <Card>
          <EyebrowLabel style={{ marginBottom: 8 }}>VaR 95% · 90 day</EyebrowLabel>
          <div style={{ fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28, color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums' }}>
            {sim.var95.toFixed(4)}
          </div>
          <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>Adverse rate move</div>
        </Card>
      </div>

      <Card eyebrow="Monte Carlo simulation" title={`${sim.pair} · 90-day history and forward distribution`} style={{ marginBottom: 16 }}>
        <FanChart
          pair={sim.pair}
          spot={sim.spot}
          budget={sim.budget}
          forwardTo={sim.forwardTo}
          days={sim.days}
          history={sim.history}
          histDays={sim.histDays}
        />
      </Card>

      <Card>
        <EyebrowLabel style={{ marginBottom: 8 }}>Risk narrative</EyebrowLabel>
        <p style={{ fontSize: 'var(--fs-body)', lineHeight: 1.65, color: 'var(--fg-1)', whiteSpace: 'pre-line' }}>
          {sim.narrative}
        </p>
        <AIDisclosure />
      </Card>
    </>
  )
}

function DraftModule({ title, description, phase3Items }) {
  return (
    <Card>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
        <EyebrowLabel>{title}</EyebrowLabel>
        <span style={{ fontSize: 'var(--fs-eyebrow)', fontWeight: 'var(--fw-bold)', letterSpacing: '0.1em', textTransform: 'uppercase', color: 'var(--snh-warning)' }}>Phase 3</span>
      </div>
      <p style={{ color: 'var(--fg-2)', fontSize: 'var(--fs-body-sm)', marginBottom: 20 }}>{description}</p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {phase3Items.map((item, i) => (
          <div key={i} style={{
            display: 'flex', alignItems: 'center', gap: 10,
            padding: '10px 14px',
            background: 'var(--snh-bg, var(--bg-page))',
            border: '1px dashed var(--border-1)',
            borderRadius: 'var(--radius-2)',
          }}>
            <Icon name="circle" size={8} style={{ color: 'var(--snh-slate)' }} />
            <span style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>{item}</span>
          </div>
        ))}
      </div>
    </Card>
  )
}

const MODULE_CONTENT = {
  'monte-carlo': <MonteCarlo />,
  'var': (
    <DraftModule
      title="Value at Risk"
      description="Portfolio-level VaR across all open exposures. Configurable confidence interval (95% / 99%) and time horizon."
      phase3Items={[
        'Historical simulation VaR — rolling 252-day window',
        'Parametric VaR — normal distribution assumption',
        'Confidence interval selector: 95% / 99%',
        'Per-currency pair breakdown',
        'Comparison vs prior month and policy limit',
      ]}
    />
  ),
  'expected-shortfall': (
    <DraftModule
      title="Expected shortfall"
      description="Conditional Value at Risk — the expected loss given that a loss exceeds the VaR threshold."
      phase3Items={[
        'ES at 95% and 99% confidence',
        'Tail distribution visualisation',
        'Per-exposure contribution to portfolio ES',
        'Comparison to VaR to surface tail severity',
      ]}
    />
  ),
  'stress-testing': (
    <DraftModule
      title="Stress testing"
      description="Apply named macro scenarios to your exposure portfolio and see the P&L impact."
      phase3Items={[
        'Named scenarios: 2008 GFC, 2015 CHF shock, COVID March 2020, custom',
        'Instantaneous and path-based shock modes',
        'Per-exposure and aggregate P&L impact',
        'Scenario config editable in Settings › Risk framework',
        'AI narrative summarising portfolio vulnerability',
      ]}
    />
  ),
  'hedge-effectiveness': (
    <DraftModule
      title="Hedge effectiveness"
      description="Measure how well your executed hedges are offsetting underlying FX risk. Required for IFRS 9 hedge accounting documentation."
      phase3Items={[
        'Dollar-offset method and regression method',
        'Prospective and retrospective effectiveness testing',
        'Per-hedge tranche effectiveness score',
        'IFRS 9 documentation export (PDF)',
        'Ineffectiveness component calculation',
      ]}
    />
  ),
}

export default function RiskEngine() {
  const [active, setActive] = useState('monte-carlo')

  return (
    <>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24 }}>
        <div>
          <EyebrowLabel>Treasury console</EyebrowLabel>
          <h2 style={{ marginTop: 8 }}>Risk engine</h2>
          <p className="caption" style={{ marginTop: 8, color: 'var(--fg-2)' }}>
            Monte Carlo · VaR · Expected shortfall · Stress testing · Hedge effectiveness
          </p>
        </div>
        <Button variant="ghost">
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <Icon name="download" size={16} /> Export report
          </span>
        </Button>
      </div>

      <div style={{ marginBottom: 24 }}>
        <Tabs
          variant="underline"
          active={active}
          onChange={setActive}
          items={MODULES.map(m => ({ id: m.id, label: m.label }))}
        />
      </div>

      {MODULE_CONTENT[active]}
    </>
  )
}
