// RiskEngine.jsx — Phase 3 (real-data port)
//
// Monte Carlo tab: wired to GET /api/monte-carlo/simulate/exposure/{id}
// BF-005 confirmed deployed 02/06/2026 — full response shape verified.
//
// Sign-off chain: Pixel → Cipher → Finn · Treasury → Lex → CEO MiniMe → Axel deploys.
// Finn · Treasury joins for this screen (FX calculations and rate display).
//
// Phase 3 scope — Monte Carlo tab:
//   - Exposure selector (fetches from enriched endpoint)
//   - Live forward_path and confidence_bands rendered via FanChart (pre-computed props)
//   - historical_rates rendered as historical line; hidden gracefully when empty ([])
//   - KPI tiles: spot, budget_rate, VaR 95%, Expected shortfall 95%
//   - vol_calibrated flag → "calibrated" / "estimated" label on ES tile
//   - AI narrative with two-tier Lex disclosure
//
// VaR, Expected shortfall, Stress testing, Hedge effectiveness:
//   Remain as Phase 3 draft placeholders — separate backend endpoints not yet built.
//   Will be wired when backend confirms spec (raise BF item at that point).

import { useState, useEffect } from 'react'
import Card from '../ui/Card'
import Button from '../ui/Button'
import EyebrowLabel from '../ui/EyebrowLabel'
import Icon from '../ui/Icon'
import Tabs from '../ui/Tabs'
import ThinkingIndicator from '../ui/ThinkingIndicator'
import FanChart from '../ui/charts/FanChart'
import { useCompany } from '../../contexts/CompanyContext'
import { API, authHeaders } from '../../utils/api'
import { monteCarloService } from '../../services/monteCarloService'

// ── Module definitions ────────────────────────────────────────────────────────
const MODULES = [
  { id: 'monte-carlo',         label: 'Monte Carlo',         live: true  },
  { id: 'var',                 label: 'VaR',                 live: false },
  { id: 'expected-shortfall',  label: 'Expected shortfall',  live: false },
  { id: 'stress-testing',      label: 'Stress testing',      live: false },
  { id: 'hedge-effectiveness', label: 'Hedge effectiveness', live: false },
]

// ── AI disclosure tag — Lex two-tier pattern ──────────────────────────────────
// ── InfoTip — inline ⓘ with popover, used on KPI tiles ───────────────────────
function InfoTip({ children }) {
  const [open, setOpen] = useState(false)
  return (
    <span style={{ position: 'relative', display: 'inline-block', marginLeft: 5 }}>
      <button
        onClick={() => setOpen(v => !v)}
        onBlur={() => setTimeout(() => setOpen(false), 150)}
        aria-label="More information"
        style={{
          background: 'none', border: 'none', padding: 0,
          cursor: 'pointer', color: 'var(--fg-3)',
          fontSize: '11px', lineHeight: 1, verticalAlign: 'middle',
        }}
      >
        ⓘ
      </button>
      {open && (
        <div style={{
          position:     'absolute',
          top:          '20px',
          left:         '50%',
          transform:    'translateX(-50%)',
          width:        '230px',
          background:   'var(--snh-navy)',
          borderRadius: 'var(--radius-2, 6px)',
          padding:      '10px 12px',
          boxShadow:    '0 4px 16px rgba(0,0,0,0.18)',
          fontSize:     'var(--fs-caption, 11px)',
          color:        'rgba(255,255,255,0.85)',
          lineHeight:   '1.55',
          zIndex:       40,
          textAlign:    'left',
          fontWeight:   400,
        }}>
          {children}
        </div>
      )}
    </span>
  )
}

function AIDisclosure() {
  return (
    <div style={{
      padding: '8px 12px',
      background: 'rgba(141,164,196,0.10)',
      borderRadius: 'var(--radius-2)',
      borderLeft: '3px solid var(--snh-slate)',
      fontSize: 'var(--fs-eyebrow)',
      color: 'var(--fg-3)',
      marginTop: 16,
    }}>
      AI-generated decision support —{' '}
      <a href="/legal" style={{ color: 'var(--snh-gold)', textDecoration: 'underline', fontWeight: 'var(--fw-bold)' }}>
        full disclosure.
      </a>
      {' '}Generated by Sumnohow's AI risk engine. This is decision support, not regulated
      investment advice. Validate against your own assessment before action.
    </div>
  )
}

// ── Finn · Treasury analytics — frontend-only derived metrics ────────────────
// Added 02 Jul 2026 per roadmap. All four derive from the existing Monte Carlo
// response (forward_path, confidence_bands, var_95_pct, expected_shortfall_95_pct)
// — no new backend endpoint. These are approximations, not the full simulation
// output (per-path data isn't returned to the client) — labelled accordingly.
// Sign-off: Finn · Treasury (methodology) → Pixel → Lex → CEO MiniMe → Axel.
//
// NOTE re: project Decimal rule — this file (like the rest of RiskEngine.jsx
// and Hedges.jsx) uses plain JS numbers, matching the existing screen's
// convention. No decimal.js dependency is currently installed; adding one is
// a dependency/architecture decision for Axel, not made here.

// Direction: receivable exposures lose when the rate falls, payable exposures
// lose when the rate rises (matches birk_api.py direction_sign convention).
function isReceivable(exposureType) {
  return (exposureType || 'payable').toLowerCase() === 'receivable'
}

// Known percentile points of the simulated rate distribution at the horizon day.
// P10/P25/P75/P90 come from the last confidence_bands entry; P50 from forward_path.
function horizonPercentiles(sim) {
  const bands = sim.confidence_bands || []
  const path  = sim.forward_path || []
  if (bands.length === 0 || path.length === 0) return null
  const lastBand = bands[bands.length - 1]
  const p50      = path[path.length - 1].rate
  return [
    { p: 10, rate: lastBand.p10 },
    { p: 25, rate: lastBand.p25 },
    { p: 50, rate: p50 },
    { p: 75, rate: lastBand.p75 },
    { p: 90, rate: lastBand.p90 },
  ]
}

// Piecewise-linear interpolation across the known percentile points to estimate
// P(rate <= target) at the horizon. Clamps outside P10–P90 rather than
// extrapolating a false-precision number.
function probRateBelow(points, target) {
  const first = points[0], last = points[points.length - 1]
  if (target <= first.rate) return { pct: first.p, clamped: 'low' }
  if (target >= last.rate)  return { pct: last.p,  clamped: 'high' }
  for (let i = 0; i < points.length - 1; i++) {
    const a = points[i], b = points[i + 1]
    if (target >= a.rate && target <= b.rate) {
      const t = (target - a.rate) / (b.rate - a.rate)
      return { pct: a.p + t * (b.p - a.p), clamped: null }
    }
  }
  return { pct: 50, clamped: null }
}

// 1. Probability of budget breach — P(the adverse side of budget_rate) at horizon.
function probabilityOfBudgetBreach(sim, exposureType) {
  const points = horizonPercentiles(sim)
  if (!points) return null
  const { pct, clamped } = probRateBelow(points, sim.budget_rate)
  const receivable = isReceivable(exposureType)
  // Receivable adverse = rate below budget → P(breach) = P(rate <= budget).
  // Payable adverse = rate above budget → P(breach) = 1 - P(rate <= budget).
  const breachPct = receivable ? pct : 100 - pct
  // Flip the clamp side to match which tail we ended up reporting.
  const breachClamped = clamped ? (receivable ? clamped : (clamped === 'low' ? 'high' : 'low')) : null
  return { pct: breachPct, clamped: breachClamped }
}

// 2. Cost at risk — Expected Shortfall expressed in money terms, in the
// company's base currency. This is the standard institutional framing (ES/CVaR
// in currency terms, not just a rate delta) — matches Finn's original spec
// (ES × notional), not the earlier probability-weighted rate-delta version.
//
// Uses the open (unhedged) amount, not gross notional — the hedged portion's
// rate is already locked and isn't exposed to this risk, consistent with how
// floating_pnl is computed server-side (birk_api.py: open_amount only).
//
// Currency conversion mirrors the backend's own from_ccy -> base_ccy pivot
// (routes/hedge_tranche_routes.py get_enriched_exposures, ~L1009-1024) rather
// than re-deriving a new rate: the enriched exposure already carries both
// total_amount (native) and total_amount_eur (base-currency), so their ratio
// *is* the from_ccy -> base rate, applied the same way the backend applies it
// to raw PnL: base_value = to_ccy_value * (from_base_rate / spot).
function costAtRiskBase(sim, exposure) {
  if (sim.expected_shortfall_95_pct == null || !exposure || !sim.spot) return null
  const { total_amount, total_amount_eur, open_amount } = exposure
  if (!total_amount || total_amount_eur == null || open_amount == null) return null

  const fromBaseRate  = total_amount_eur / total_amount   // from_ccy -> base_ccy
  const costToCcy     = Math.abs(sim.expected_shortfall_95_pct) * open_amount  // in to_currency, per (rate x from_ccy amount) convention
  return costToCcy * (fromBaseRate / sim.spot)
}

// 3. Days to first breach — first day the median (P50) forward path crosses to
// the adverse side of budget_rate. Approximate: the true "median day across all
// simulated paths" needs per-path data the API doesn't return; this uses the
// single median path instead, labelled as such in the tile caption.
function daysToFirstBreach(sim, exposureType) {
  const path = sim.forward_path || []
  if (path.length === 0) return null
  const receivable = isReceivable(exposureType)
  const breaches = (rate) => receivable ? rate < sim.budget_rate : rate > sim.budget_rate
  const hit = path.find(p => breaches(p.rate))
  return hit ? hit.day : null // null = median path does not cross budget within horizon
}

// 4. Optimal hedge ratio — Finn's formula, direction-adjusted. The version
// circulated as "1 - P50/budget_rate" is correct for receivables (hedge more
// when the median outcome is expected below budget) but inverts for payables,
// where the adverse side is P50 above budget — flagged for Finn to confirm.
function optimalHedgeRatio(sim, exposureType) {
  const path = sim.forward_path || []
  if (path.length === 0 || !sim.budget_rate) return null
  const p50 = path[path.length - 1].rate
  const raw = isReceivable(exposureType)
    ? 1 - (p50 / sim.budget_rate)
    : (p50 / sim.budget_rate) - 1
  return Math.min(1, Math.max(0, raw)) * 100
}

// ── Monte Carlo tab — Phase 3 live data ───────────────────────────────────────
function MonteCarlo() {
  const { selectedCompanyId, getSelectedCompany } = useCompany()
  const baseCcy = getSelectedCompany()?.base_currency || 'EUR'

  // Exposures list for the selector
  const [exposures, setExposures]     = useState([])
  const [expLoading, setExpLoading]   = useState(true)

  // Selected exposure and simulation result
  const [selectedId, setSelectedId]   = useState(null)
  const [sim, setSim]                 = useState(null)
  const [simLoading, setSimLoading]   = useState(false)
  const [simError, setSimError]       = useState(null)

  // ── Fetch active exposures on mount / company change ──────────────────────
  useEffect(() => {
    if (!selectedCompanyId) return

    setExpLoading(true)
    fetch(API.exposuresEnriched(selectedCompanyId), {
      headers: authHeaders(),
      credentials: 'include',
    })
      .then(r => r.json())
      .then(data => {
        // Enriched endpoint returns { items: [...], portfolio: {...} }
        const items = Array.isArray(data) ? data : (data.items || [])
        // Only active, non-settled exposures
        const active = items.filter(e => e.is_active !== false && e.tab !== 'settled')
        setExposures(active)
        if (active.length > 0) setSelectedId(active[0].id)
      })
      .catch(err => {
        console.error('RiskEngine: failed to fetch exposures', err)
        setExposures([])
      })
      .finally(() => setExpLoading(false))
  }, [selectedCompanyId])

  // ── Run simulation when selected exposure changes ─────────────────────────
  useEffect(() => {
    if (!selectedId) return

    setSimLoading(true)
    setSim(null)
    setSimError(null)

    monteCarloService.runSimulation(selectedId)
      .then(data => setSim(data))
      .catch(err => setSimError(err.message || 'Simulation unavailable'))
      .finally(() => setSimLoading(false))
  }, [selectedId])

  // ── Derived display values ────────────────────────────────────────────────
  // historical_rates may be [] for pairs not yet seeded — hide gracefully
  const hasHistory     = sim && Array.isArray(sim.historical_rates) && sim.historical_rates.length > 0
  const histDaysActual = hasHistory ? Math.abs(sim.historical_rates[0].day) : 0

  // ── Finn analytics — derived from sim + the selected exposure's direction ──
  const selectedExposure = exposures.find(e => e.id === selectedId)
  const exposureType     = selectedExposure?.exposure_type || 'payable'
  const breach       = sim ? probabilityOfBudgetBreach(sim, exposureType) : null
  const costRisk      = sim ? costAtRiskBase(sim, selectedExposure) : null
  const daysToBreach  = sim ? daysToFirstBreach(sim, exposureType) : null
  const hedgeRatio    = sim ? optimalHedgeRatio(sim, exposureType) : null

  // ── Render ─────────────────────────────────────────────────────────────────
  if (expLoading) {
    return <ThinkingIndicator />
  }

  if (exposures.length === 0) {
    return (
      <Card>
        <p style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>
          No active exposures found. Add an exposure to run a simulation.
        </p>
      </Card>
    )
  }

  return (
    <>
      {/* ── Exposure selector ──────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <EyebrowLabel>Exposure</EyebrowLabel>
        <select
          value={selectedId || ''}
          onChange={e => setSelectedId(Number(e.target.value))}
          style={{
            fontFamily:  'var(--font-body)',
            fontSize:    'var(--fs-body-sm)',
            padding:     '6px 10px',
            border:      '1px solid var(--border-1)',
            borderRadius:'var(--radius-2)',
            background:  'var(--bg-surface)',
            color:       'var(--fg-1)',
            cursor:      'pointer',
          }}
        >
          {exposures.map(e => (
            <option key={e.id} value={e.id}>
              {e.pair || e.currency_pair || '—'} · {e.description || `Exposure ${e.id}`}
            </option>
          ))}
        </select>
      </div>

      {/* ── Loading state ──────────────────────────────────────────────────── */}
      {simLoading && <ThinkingIndicator />}

      {/* ── Error state ────────────────────────────────────────────────────── */}
      {simError && !simLoading && (
        <Card>
          <p style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>
            Simulation unavailable — {simError}
          </p>
        </Card>
      )}

      {/* ── Results ────────────────────────────────────────────────────────── */}
      {sim && !simLoading && (
        <>
          {/* KPI row */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 16 }}>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Spot rate
                <InfoTip>
                  <strong>Spot rate</strong><br />
                  The current mid-market exchange rate for {sim.pair}. Sourced from the live rate feed and used as the starting point for the Monte Carlo simulation.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.spot).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                {sim.pair} · live
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Budget rate
                <InfoTip>
                  <strong>Budget rate</strong><br />
                  The exchange rate used when this exposure was originally planned or budgeted. The simulation shows the probability that the rate will remain favourable relative to this level.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-gold)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.budget_rate).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                Planning benchmark
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                VaR 95% · {sim.horizon_days || 90} day
                <InfoTip>
                  <strong>Value at Risk (VaR 95%)</strong><br />
                  The worst adverse rate move expected over the {sim.horizon_days || 90}-day horizon in 95% of simulated scenarios. In the remaining 5% of scenarios, the move could be larger. This is not a maximum loss.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.var_95_pct).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                Adverse rate move (P5)
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Expected shortfall 95%
                <InfoTip>
                  <strong>Expected Shortfall (CVaR 95%)</strong><br />
                  The average rate move in the worst 5% of simulated scenarios — more conservative than VaR. Shows what to expect if things do go wrong, not just the threshold.<br /><br />
                  <em>Vol {sim.vol_calibrated ? 'calibrated' : 'estimated'}:</em> {sim.vol_calibrated
                    ? 'Volatility was estimated from actual historical price data for this pair.'
                    : 'Insufficient history — a default volatility assumption was used.'}
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.expected_shortfall_95_pct).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                CVaR · vol {sim.vol_calibrated ? 'calibrated' : 'estimated'}
              </div>
            </Card>

          </div>

          {/* Finn · Treasury analytics — frontend-derived, second KPI row */}
          <div style={{ marginBottom: 8 }}>
            <EyebrowLabel style={{ color: 'var(--fg-3)' }}>Analytics</EyebrowLabel>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 16 }}>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Probability of budget breach
                <InfoTip>
                  <strong>Probability of budget breach</strong><br />
                  Estimated chance the {sim.horizon_days || 90}-day rate ends up on the adverse
                  side of your budget rate ({exposureType === 'receivable' ? 'below' : 'above'} {Number(sim.budget_rate).toFixed(4)}
                  {' '}for a {exposureType} exposure). Interpolated from the simulation's P10–P90
                  bands — an approximation, not the full path distribution.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums',
              }}>
                {breach == null ? '—' : `${breach.clamped === 'low' ? '<' : breach.clamped === 'high' ? '>' : ''}${Math.round(breach.pct)}%`}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                {exposureType === 'receivable' ? 'Rate below budget' : 'Rate above budget'} at horizon
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Cost at risk
                <InfoTip>
                  <strong>Cost at risk</strong><br />
                  Expected Shortfall (the average adverse rate move in the worst 5% of scenarios)
                  applied to the open, unhedged amount and converted to {baseCcy} — the standard
                  CVaR-in-money-terms framing used in board and bank risk reporting. The hedged
                  portion of this exposure carries a locked rate and isn't included, since it
                  isn't exposed to this risk.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums',
              }}>
                {costRisk == null ? '—' : `${baseCcy} ${Math.round(costRisk).toLocaleString('en-GB')}`}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                ES 95% on open amount
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Days to first breach
                <InfoTip>
                  <strong>Days to first breach</strong><br />
                  First day the median (P50) projected path crosses to the adverse side of
                  budget. Based on the single median path, not the median across all simulated
                  paths — the API does not return per-path data to the client.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums',
              }}>
                {daysToBreach == null ? `No breach · ${sim.horizon_days || 90}d` : `${daysToBreach}d`}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                On the median (P50) path
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Optimal hedge ratio
                <InfoTip>
                  <strong>Optimal hedge ratio</strong><br />
                  1 − P50/budget for receivables, P50/budget − 1 for payables, bounded 0–100%.
                  Higher when the median projected outcome is expected to land on the adverse
                  side of budget. A starting point for discussion, not a policy recommendation.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-gold)', fontVariantNumeric: 'tabular-nums',
              }}>
                {hedgeRatio == null ? '—' : `${Math.round(hedgeRatio)}%`}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                Suggested cover, median scenario
              </div>
            </Card>

          </div>

          {/* Fan chart — uses pre-computed GBM paths from API */}
          <Card
            eyebrow="Monte Carlo simulation"
            title={`${sim.pair} · ${sim.horizon_days || 90}-day forward distribution`}
            style={{ marginBottom: 16 }}
          >
            <FanChart
              pair={sim.pair}
              spot={Number(sim.spot)}
              budget={Number(sim.budget_rate)}
              days={sim.horizon_days || 90}
              history={hasHistory ? sim.historical_rates : null}
              histDays={histDaysActual}
              forwardPath={sim.forward_path}
              confidenceBands={sim.confidence_bands}
              height={160}
              showHeader={false}
            />
            {!hasHistory && (
              <p style={{
                marginTop: 12,
                fontSize: 'var(--fs-eyebrow)',
                color: 'var(--fg-3)',
              }}>
                Historical rate data not yet available for this pair — chart shows forward projection only.
              </p>
            )}
          </Card>

          {/* AI narrative — shown when backend returns one */}
          {sim.narrative && (
            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>Risk narrative</EyebrowLabel>
              <p style={{
                fontSize: 'var(--fs-body)',
                lineHeight: 1.65,
                color: 'var(--fg-1)',
                whiteSpace: 'pre-line',
              }}>
                {sim.narrative}
              </p>
              <AIDisclosure />
            </Card>
          )}
        </>
      )}
    </>
  )
}

// ── DRAFT placeholder — Phase 3 modules not yet built ────────────────────────
function DraftModule({ title, description, phase3Items }) {
  return (
    <Card>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
        <EyebrowLabel>{title}</EyebrowLabel>
        <span style={{
          fontSize: 'var(--fs-eyebrow)', fontWeight: 'var(--fw-bold)',
          letterSpacing: '0.1em', textTransform: 'uppercase',
          color: 'var(--snh-warning)',
        }}>Phase 3</span>
      </div>
      <p style={{ color: 'var(--fg-2)', fontSize: 'var(--fs-body-sm)', marginBottom: 20 }}>
        {description}
      </p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {phase3Items.map((item, i) => (
          <div key={i} style={{
            display: 'flex', alignItems: 'center', gap: 10,
            padding: '10px 14px',
            background: 'var(--snh-bg, var(--bg-page))',
            border: '1px dashed var(--border-1)',
            borderRadius: 'var(--radius-2)',
          }}>
            <Icon name="circle" size={8} style={{ color: 'var(--snh-slate)' }} />
            <span style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>{item}</span>
          </div>
        ))}
      </div>
    </Card>
  )
}

// ── Module registry ───────────────────────────────────────────────────────────
const MODULE_CONTENT = {
  'monte-carlo': <MonteCarlo />,

  'var': (
    <DraftModule
      title="Value at Risk"
      description="Portfolio-level VaR across all open exposures. Configurable confidence interval (95% / 99%) and time horizon. Designed for board reporting and internal risk limits."
      phase3Items={[
        'Historical simulation VaR — rolling 252-day window',
        'Parametric VaR — normal distribution assumption',
        'Confidence interval selector: 95% / 99%',
        'Per-currency pair breakdown',
        'Comparison vs prior month and policy limit',
      ]}
    />
  ),

  'expected-shortfall': (
    <DraftModule
      title="Expected shortfall"
      description="Conditional Value at Risk — the expected loss given that a loss exceeds the VaR threshold. More sensitive to tail risk than VaR alone."
      phase3Items={[
        'ES at 95% and 99% confidence',
        'Tail distribution visualisation',
        'Per-exposure contribution to portfolio ES',
        'Comparison to VaR to surface tail severity',
      ]}
    />
  ),

  'stress-testing': (
    <DraftModule
      title="Stress testing"
      description="Apply named macro scenarios to your exposure portfolio and see the P&L impact. Scenarios sourced from the Settings risk framework — editable by your treasury team."
      phase3Items={[
        'Named scenarios: 2008 GFC, 2015 CHF shock, COVID March 2020, custom',
        'Instantaneous and path-based shock modes',
        'Per-exposure and aggregate P&L impact',
        'Scenario config editable in Settings › Risk framework',
        'AI narrative summarising portfolio vulnerability',
      ]}
    />
  ),

  'hedge-effectiveness': (
    <DraftModule
      title="Hedge effectiveness"
      description="Measure how well your executed hedges are offsetting underlying FX risk. Required for IFRS 9 hedge accounting documentation."
      phase3Items={[
        'Dollar-offset method and regression method',
        'Prospective and retrospective effectiveness testing',
        'Per-hedge tranche effectiveness score',
        'IFRS 9 documentation export (PDF)',
        'Ineffectiveness component calculation',
      ]}
    />
  ),
}

// ── Main screen ───────────────────────────────────────────────────────────────
// Note: MODULE_CONTENT is defined at module level so DraftModule instances are
// stable. MonteCarlo is defined as a component and rendered here so it can use
// hooks (useCompany, useState, useEffect).

export default function RiskEngine() {
  const [active, setActive] = useState('monte-carlo')

  return (
    <>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24 }}>
        <div>
          <EyebrowLabel>Treasury console</EyebrowLabel>
          <h2 style={{ marginTop: 8 }}>Risk engine</h2>
          <p className="caption" style={{ marginTop: 8, color: 'var(--fg-2)' }}>
            Monte Carlo · VaR · Expected shortfall · Stress testing · Hedge effectiveness
          </p>
        </div>
        <Button variant="ghost">
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <Icon name="download" size={16} /> Export report
          </span>
        </Button>
      </div>

      {/* Module tabs */}
      <div style={{ marginBottom: 24 }}>
        <Tabs
          variant="underline"
          active={active}
          onChange={setActive}
          items={MODULES.map(m => ({ id: m.id, label: m.label }))}
        />
      </div>

      {/* Active module */}
      {active === 'monte-carlo' ? <MonteCarlo /> : MODULE_CONTENT[active]}
    </>
  )
}