// RiskEngine.jsx — Phase 3 (real-data port)
//
// Monte Carlo tab: wired to GET /api/monte-carlo/simulate/exposure/{id}
// BF-005 confirmed deployed 02/06/2026 — full response shape verified.
//
// Sign-off chain: Pixel → Cipher → Finn · Treasury → Lex → CEO MiniMe → Axel deploys.
// Finn · Treasury joins for this screen (FX calculations and rate display).
//
// Phase 3 scope — Monte Carlo tab:
//   - Exposure selector (fetches from enriched endpoint)
//   - Live forward_path and confidence_bands rendered via FanChart (pre-computed props)
//   - historical_rates rendered as historical line; hidden gracefully when empty ([])
//   - KPI tiles: spot, budget_rate, VaR 95%, Expected shortfall 95%
//   - vol_calibrated flag → "calibrated" / "estimated" label on ES tile
//   - AI narrative with two-tier Lex disclosure
//
// VaR, Expected shortfall, Stress testing, Hedge effectiveness:
//   Remain as Phase 3 draft placeholders — separate backend endpoints not yet built.
//   Will be wired when backend confirms spec (raise BF item at that point).

import { useState, useEffect } from 'react'
import Card from '../ui/Card'
import Button from '../ui/Button'
import EyebrowLabel from '../ui/EyebrowLabel'
import Icon from '../ui/Icon'
import Tabs from '../ui/Tabs'
import ThinkingIndicator from '../ui/ThinkingIndicator'
import FanChart from '../ui/charts/FanChart'
import { useCompany } from '../../contexts/CompanyContext'
import { API, authHeaders } from '../../utils/api'
import { monteCarloService } from '../../services/monteCarloService'

// ── Module definitions ────────────────────────────────────────────────────────
const MODULES = [
  { id: 'monte-carlo',         label: 'Monte Carlo',         live: true  },
  { id: 'var',                 label: 'VaR',                 live: false },
  { id: 'expected-shortfall',  label: 'Expected shortfall',  live: false },
  { id: 'stress-testing',      label: 'Stress testing',      live: false },
  { id: 'hedge-effectiveness', label: 'Hedge effectiveness', live: false },
]

// ── AI disclosure tag — Lex two-tier pattern ──────────────────────────────────
// ── InfoTip — inline ⓘ with popover, used on KPI tiles ───────────────────────
function InfoTip({ children }) {
  const [open, setOpen] = useState(false)
  return (
    <span style={{ position: 'relative', display: 'inline-block', marginLeft: 5 }}>
      <button
        onClick={() => setOpen(v => !v)}
        onBlur={() => setTimeout(() => setOpen(false), 150)}
        aria-label="More information"
        style={{
          background: 'none', border: 'none', padding: 0,
          cursor: 'pointer', color: 'var(--fg-3)',
          fontSize: '11px', lineHeight: 1, verticalAlign: 'middle',
        }}
      >
        ⓘ
      </button>
      {open && (
        <div style={{
          position:     'absolute',
          top:          '20px',
          left:         '50%',
          transform:    'translateX(-50%)',
          width:        '230px',
          background:   'var(--snh-navy)',
          borderRadius: 'var(--radius-2, 6px)',
          padding:      '10px 12px',
          boxShadow:    '0 4px 16px rgba(0,0,0,0.18)',
          fontSize:     'var(--fs-caption, 11px)',
          color:        'rgba(255,255,255,0.85)',
          lineHeight:   '1.55',
          zIndex:       40,
          textAlign:    'left',
          fontWeight:   400,
        }}>
          {children}
        </div>
      )}
    </span>
  )
}

function AIDisclosure() {
  return (
    <div style={{
      padding: '8px 12px',
      background: 'rgba(141,164,196,0.10)',
      borderRadius: 'var(--radius-2)',
      borderLeft: '3px solid var(--snh-slate)',
      fontSize: 'var(--fs-eyebrow)',
      color: 'var(--fg-3)',
      marginTop: 16,
    }}>
      AI-generated decision support —{' '}
      <a href="/legal" style={{ color: 'var(--snh-gold)', textDecoration: 'underline', fontWeight: 'var(--fw-bold)' }}>
        full disclosure.
      </a>
      {' '}Generated by Sumnohow's AI risk engine. This is decision support, not regulated
      investment advice. Validate against your own assessment before action.
    </div>
  )
}

// ── Monte Carlo tab — Phase 3 live data ───────────────────────────────────────
function MonteCarlo() {
  const { selectedCompanyId } = useCompany()

  // Exposures list for the selector
  const [exposures, setExposures]     = useState([])
  const [expLoading, setExpLoading]   = useState(true)

  // Selected exposure and simulation result
  const [selectedId, setSelectedId]   = useState(null)
  const [sim, setSim]                 = useState(null)
  const [simLoading, setSimLoading]   = useState(false)
  const [simError, setSimError]       = useState(null)

  // ── Fetch active exposures on mount / company change ──────────────────────
  useEffect(() => {
    if (!selectedCompanyId) return

    setExpLoading(true)
    fetch(API.exposuresEnriched(selectedCompanyId), {
      headers: authHeaders(),
      credentials: 'include',
    })
      .then(r => r.json())
      .then(data => {
        // Enriched endpoint returns { items: [...], portfolio: {...} }
        const items = Array.isArray(data) ? data : (data.items || [])
        // Only active, non-settled exposures
        const active = items.filter(e => e.is_active !== false && e.tab !== 'settled')
        setExposures(active)
        if (active.length > 0) setSelectedId(active[0].id)
      })
      .catch(err => {
        console.error('RiskEngine: failed to fetch exposures', err)
        setExposures([])
      })
      .finally(() => setExpLoading(false))
  }, [selectedCompanyId])

  // ── Run simulation when selected exposure changes ─────────────────────────
  useEffect(() => {
    if (!selectedId) return

    setSimLoading(true)
    setSim(null)
    setSimError(null)

    monteCarloService.runSimulation(selectedId)
      .then(data => setSim(data))
      .catch(err => setSimError(err.message || 'Simulation unavailable'))
      .finally(() => setSimLoading(false))
  }, [selectedId])

  // ── Derived display values ────────────────────────────────────────────────
  // historical_rates may be [] for pairs not yet seeded — hide gracefully
  const hasHistory     = sim && Array.isArray(sim.historical_rates) && sim.historical_rates.length > 0
  const histDaysActual = hasHistory ? Math.abs(sim.historical_rates[0].day) : 0

  // ── Render ─────────────────────────────────────────────────────────────────
  if (expLoading) {
    return <ThinkingIndicator />
  }

  if (exposures.length === 0) {
    return (
      <Card>
        <p style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>
          No active exposures found. Add an exposure to run a simulation.
        </p>
      </Card>
    )
  }

  return (
    <>
      {/* ── Exposure selector ──────────────────────────────────────────────── */}
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
        <EyebrowLabel>Exposure</EyebrowLabel>
        <select
          value={selectedId || ''}
          onChange={e => setSelectedId(Number(e.target.value))}
          style={{
            fontFamily:  'var(--font-body)',
            fontSize:    'var(--fs-body-sm)',
            padding:     '6px 10px',
            border:      '1px solid var(--border-1)',
            borderRadius:'var(--radius-2)',
            background:  'var(--bg-surface)',
            color:       'var(--fg-1)',
            cursor:      'pointer',
          }}
        >
          {exposures.map(e => (
            <option key={e.id} value={e.id}>
              {e.pair || e.currency_pair || '—'} · {e.description || `Exposure ${e.id}`}
            </option>
          ))}
        </select>
      </div>

      {/* ── Loading state ──────────────────────────────────────────────────── */}
      {simLoading && <ThinkingIndicator />}

      {/* ── Error state ────────────────────────────────────────────────────── */}
      {simError && !simLoading && (
        <Card>
          <p style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>
            Simulation unavailable — {simError}
          </p>
        </Card>
      )}

      {/* ── Results ────────────────────────────────────────────────────────── */}
      {sim && !simLoading && (
        <>
          {/* KPI row */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 16, marginBottom: 16 }}>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Spot rate
                <InfoTip>
                  <strong>Spot rate</strong><br />
                  The current mid-market exchange rate for {sim.pair}. Sourced from the live rate feed and used as the starting point for the Monte Carlo simulation.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-navy)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.spot).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                {sim.pair} · live
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Budget rate
                <InfoTip>
                  <strong>Budget rate</strong><br />
                  The exchange rate used when this exposure was originally planned or budgeted. The simulation shows the probability that the rate will remain favourable relative to this level.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-gold)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.budget_rate).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                Planning benchmark
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                VaR 95% · {sim.horizon_days || 90} day
                <InfoTip>
                  <strong>Value at Risk (VaR 95%)</strong><br />
                  The worst adverse rate move expected over the {sim.horizon_days || 90}-day horizon in 95% of simulated scenarios. In the remaining 5% of scenarios, the move could be larger. This is not a maximum loss.
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.var_95_pct).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                Adverse rate move (P5)
              </div>
            </Card>

            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>
                Expected shortfall 95%
                <InfoTip>
                  <strong>Expected Shortfall (CVaR 95%)</strong><br />
                  The average rate move in the worst 5% of simulated scenarios — more conservative than VaR. Shows what to expect if things do go wrong, not just the threshold.<br /><br />
                  <em>Vol {sim.vol_calibrated ? 'calibrated' : 'estimated'}:</em> {sim.vol_calibrated
                    ? 'Volatility was estimated from actual historical price data for this pair.'
                    : 'Insufficient history — a default volatility assumption was used.'}
                </InfoTip>
              </EyebrowLabel>
              <div style={{
                fontFamily: 'var(--font-display)', fontWeight: 700, fontSize: 28,
                color: 'var(--snh-danger)', fontVariantNumeric: 'tabular-nums',
              }}>
                {Number(sim.expected_shortfall_95_pct).toFixed(4)}
              </div>
              <div className="caption" style={{ marginTop: 4, color: 'var(--fg-2)' }}>
                CVaR · vol {sim.vol_calibrated ? 'calibrated' : 'estimated'}
              </div>
            </Card>

          </div>

          {/* Fan chart — uses pre-computed GBM paths from API */}
          <Card
            eyebrow="Monte Carlo simulation"
            title={`${sim.pair} · ${sim.horizon_days || 90}-day forward distribution`}
            style={{ marginBottom: 16 }}
          >
            <FanChart
              pair={sim.pair}
              spot={Number(sim.spot)}
              budget={Number(sim.budget_rate)}
              days={sim.horizon_days || 90}
              history={hasHistory ? sim.historical_rates : null}
              histDays={histDaysActual}
              forwardPath={sim.forward_path}
              confidenceBands={sim.confidence_bands}
              height={160}
              showHeader={false}
            />
            {!hasHistory && (
              <p style={{
                marginTop: 12,
                fontSize: 'var(--fs-eyebrow)',
                color: 'var(--fg-3)',
              }}>
                Historical rate data not yet available for this pair — chart shows forward projection only.
              </p>
            )}
          </Card>

          {/* AI narrative — shown when backend returns one */}
          {sim.narrative && (
            <Card>
              <EyebrowLabel style={{ marginBottom: 8 }}>Risk narrative</EyebrowLabel>
              <p style={{
                fontSize: 'var(--fs-body)',
                lineHeight: 1.65,
                color: 'var(--fg-1)',
                whiteSpace: 'pre-line',
              }}>
                {sim.narrative}
              </p>
              <AIDisclosure />
            </Card>
          )}
        </>
      )}
    </>
  )
}

// ── DRAFT placeholder — Phase 3 modules not yet built ────────────────────────
function DraftModule({ title, description, phase3Items }) {
  return (
    <Card>
      <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 12 }}>
        <EyebrowLabel>{title}</EyebrowLabel>
        <span style={{
          fontSize: 'var(--fs-eyebrow)', fontWeight: 'var(--fw-bold)',
          letterSpacing: '0.1em', textTransform: 'uppercase',
          color: 'var(--snh-warning)',
        }}>Phase 3</span>
      </div>
      <p style={{ color: 'var(--fg-2)', fontSize: 'var(--fs-body-sm)', marginBottom: 20 }}>
        {description}
      </p>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {phase3Items.map((item, i) => (
          <div key={i} style={{
            display: 'flex', alignItems: 'center', gap: 10,
            padding: '10px 14px',
            background: 'var(--snh-bg, var(--bg-page))',
            border: '1px dashed var(--border-1)',
            borderRadius: 'var(--radius-2)',
          }}>
            <Icon name="circle" size={8} style={{ color: 'var(--snh-slate)' }} />
            <span style={{ fontSize: 'var(--fs-body-sm)', color: 'var(--fg-2)' }}>{item}</span>
          </div>
        ))}
      </div>
    </Card>
  )
}

// ── Module registry ───────────────────────────────────────────────────────────
const MODULE_CONTENT = {
  'monte-carlo': <MonteCarlo />,

  'var': (
    <DraftModule
      title="Value at Risk"
      description="Portfolio-level VaR across all open exposures. Configurable confidence interval (95% / 99%) and time horizon. Designed for board reporting and internal risk limits."
      phase3Items={[
        'Historical simulation VaR — rolling 252-day window',
        'Parametric VaR — normal distribution assumption',
        'Confidence interval selector: 95% / 99%',
        'Per-currency pair breakdown',
        'Comparison vs prior month and policy limit',
      ]}
    />
  ),

  'expected-shortfall': (
    <DraftModule
      title="Expected shortfall"
      description="Conditional Value at Risk — the expected loss given that a loss exceeds the VaR threshold. More sensitive to tail risk than VaR alone."
      phase3Items={[
        'ES at 95% and 99% confidence',
        'Tail distribution visualisation',
        'Per-exposure contribution to portfolio ES',
        'Comparison to VaR to surface tail severity',
      ]}
    />
  ),

  'stress-testing': (
    <DraftModule
      title="Stress testing"
      description="Apply named macro scenarios to your exposure portfolio and see the P&L impact. Scenarios sourced from the Settings risk framework — editable by your treasury team."
      phase3Items={[
        'Named scenarios: 2008 GFC, 2015 CHF shock, COVID March 2020, custom',
        'Instantaneous and path-based shock modes',
        'Per-exposure and aggregate P&L impact',
        'Scenario config editable in Settings › Risk framework',
        'AI narrative summarising portfolio vulnerability',
      ]}
    />
  ),

  'hedge-effectiveness': (
    <DraftModule
      title="Hedge effectiveness"
      description="Measure how well your executed hedges are offsetting underlying FX risk. Required for IFRS 9 hedge accounting documentation."
      phase3Items={[
        'Dollar-offset method and regression method',
        'Prospective and retrospective effectiveness testing',
        'Per-hedge tranche effectiveness score',
        'IFRS 9 documentation export (PDF)',
        'Ineffectiveness component calculation',
      ]}
    />
  ),
}

// ── Main screen ───────────────────────────────────────────────────────────────
// Note: MODULE_CONTENT is defined at module level so DraftModule instances are
// stable. MonteCarlo is defined as a component and rendered here so it can use
// hooks (useCompany, useState, useEffect).

export default function RiskEngine() {
  const [active, setActive] = useState('monte-carlo')

  return (
    <>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end', marginBottom: 24 }}>
        <div>
          <EyebrowLabel>Treasury console</EyebrowLabel>
          <h2 style={{ marginTop: 8 }}>Risk engine</h2>
          <p className="caption" style={{ marginTop: 8, color: 'var(--fg-2)' }}>
            Monte Carlo · VaR · Expected shortfall · Stress testing · Hedge effectiveness
          </p>
        </div>
        <Button variant="ghost">
          <span style={{ display: 'inline-flex', alignItems: 'center', gap: 8 }}>
            <Icon name="download" size={16} /> Export report
          </span>
        </Button>
      </div>

      {/* Module tabs */}
      <div style={{ marginBottom: 24 }}>
        <Tabs
          variant="underline"
          active={active}
          onChange={setActive}
          items={MODULES.map(m => ({ id: m.id, label: m.label }))}
        />
      </div>

      {/* Active module */}
      {active === 'monte-carlo' ? <MonteCarlo /> : MODULE_CONTENT[active]}
    </>
  )
}
