"""
services/market_report_pdf.py

Generates a branded PDF for the weekly FX market report.
Uses ReportLab — same library as services/pdf_service.py (Currency Plan PDF).

Structure:
  Page 1  — Cover (NAVY full-page, SUMNOHOW logo, company name, date, CONFIDENTIAL)
  Page 2  — Executive Summary (headline, portfolio impact, risk alert)
  Page 3+ — Currency Pair Analysis (one section per pair)
  Last    — Economic Calendar + Disclaimer

Footer on every page: "Generated by Sumnohow AI Engine" + page number.
"""

import io
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor, white, black
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table,
    TableStyle, PageBreak, HRFlowable, KeepTogether,
)
from reportlab.lib.enums import TA_LEFT, TA_RIGHT, TA_CENTER

# ── Brand colours (match brand.js) ───────────────────────────────────────────
NAVY    = HexColor('#1A2744')
NAVY_LT = HexColor('#243560')
GOLD    = HexColor('#C9A86C')
DANGER  = HexColor('#EF4444')
WARNING = HexColor('#F59E0B')
SUCCESS = HexColor('#10B981')
LIGHT   = HexColor('#F4F6FA')
GREY    = HexColor('#6C757D')
BODY    = HexColor('#374151')
MUTED   = HexColor('#9CA3AF')

DISCLAIMER_TEXT = (
    "This report is generated by the Sumnohow AI engine for informational purposes only. "
    "It does not constitute financial advice or a recommendation to execute any transaction. "
    "All hedging decisions should be made in consultation with your treasury team and banking "
    "partners. Rates shown are indicative only."
)

IMPACT_COLORS = {
    "High":   DANGER,
    "Medium": WARNING,
    "Low":    GREY,
}

# Minimal currency flags for PDF (emoji not supported by base ReportLab fonts)
CURRENCY_FLAG = {
    "EUR": "EU",  "GBP": "GB",  "USD": "US",  "NOK": "NO",
    "SEK": "SE",  "DKK": "DK",  "CHF": "CH",  "JPY": "JP",
    "AUD": "AU",  "CAD": "CA",  "NZD": "NZ",  "SGD": "SG",
}


def generate_market_report_pdf(report: dict, company_name: str) -> bytes:
    """
    Generate a branded PDF for a market report dict as returned by
    generate_market_report() / the GET /api/reports/market/{id} endpoint.

    Returns raw PDF bytes.
    """
    content = report.get("content", {})
    report_date = report.get("report_date", date.today().isoformat())
    try:
        date_display = date.fromisoformat(report_date).strftime("%d %B %Y")
    except Exception:
        date_display = report_date

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=18 * mm,
        leftMargin=18 * mm,
        topMargin=16 * mm,
        bottomMargin=22 * mm,  # extra bottom space for footer
    )

    # ── Styles ────────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    def s(name, **kw):
        return ParagraphStyle(name, parent=base["Normal"], **kw)

    cover_logo  = s("CL",  fontSize=28, textColor=GOLD, fontName="Helvetica-Bold",
                    alignment=TA_CENTER, spaceAfter=4)
    cover_title = s("CT",  fontSize=14, textColor=white, fontName="Helvetica",
                    alignment=TA_CENTER, spaceAfter=8)
    cover_sub   = s("CS",  fontSize=10, textColor=HexColor("#8DA4C4"),
                    fontName="Helvetica", alignment=TA_CENTER, spaceAfter=4)
    cover_conf  = s("CC",  fontSize=9, textColor=GOLD, fontName="Helvetica-Bold",
                    alignment=TA_CENTER, letterSpacing=3)

    h1     = s("H1",  fontSize=14, textColor=NAVY, fontName="Helvetica-Bold",
                spaceAfter=6, spaceBefore=12)
    h2     = s("H2",  fontSize=10, textColor=GOLD,  fontName="Helvetica-Bold",
                spaceAfter=4, spaceBefore=8, leading=14)
    h2_sm  = s("H2S", fontSize=8, textColor=GOLD,   fontName="Helvetica-Bold",
                spaceAfter=3, spaceBefore=6, leading=12)
    body   = s("BD",  fontSize=9, textColor=BODY,   fontName="Helvetica",
                spaceAfter=4, leading=14)
    small  = s("SM",  fontSize=7, textColor=MUTED,  fontName="Helvetica",
                spaceAfter=2, leading=11)
    right  = s("RT",  fontSize=9, textColor=MUTED,  fontName="Helvetica",
                alignment=TA_RIGHT)
    pair_h = s("PH",  fontSize=11, textColor=white, fontName="Helvetica-Bold")
    pair_m = s("PM",  fontSize=9,  textColor=white, fontName="Helvetica",
                alignment=TA_RIGHT)
    action_s = s("AC", fontSize=8, textColor=HexColor("#92711A"),
                 fontName="Helvetica-Bold", leading=12)

    story = []

    # ── PAGE 1: COVER ─────────────────────────────────────────────────────────
    # Simulate full-page cover with a tall NAVY table
    PAGE_H = A4[1] - doc.topMargin - doc.bottomMargin  # available height

    cover_inner = [
        [Spacer(1, 20 * mm)],
        [Paragraph("SUMNOHOW", cover_logo)],
        [Spacer(1, 6 * mm)],
        [Paragraph("Weekly FX Market Report", cover_title)],
        [Spacer(1, 3 * mm)],
        [Paragraph(company_name.upper(), cover_sub)],
        [Paragraph(f"Week ending {date_display}", cover_sub)],
        [Spacer(1, 16 * mm)],
        [HRFlowable(width=60 * mm, thickness=1, color=GOLD,
                    spaceAfter=16 * mm, hAlign="CENTER")],
        [Paragraph("CONFIDENTIAL", cover_conf)],
    ]
    cover_tbl = Table(cover_inner, colWidths=[174 * mm])
    cover_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), NAVY),
        ("ROWHEIGHT",     (0, 0), (-1, -1), None),  # let content size rows
        ("TOPPADDING",    (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
        ("LEFTPADDING",   (0, 0), (-1, -1), 0),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 0),
    ]))
    story.append(cover_tbl)
    story.append(PageBreak())

    # ── PAGE 2: EXECUTIVE SUMMARY ─────────────────────────────────────────────
    story.append(Paragraph("Executive Summary", h1))
    story.append(HRFlowable(width="100%", thickness=0.5, color=GOLD, spaceAfter=6 * mm))

    headline = content.get("headline", "")
    if headline:
        story.append(Paragraph(headline, s("HL", fontSize=11, textColor=NAVY,
                                            fontName="Helvetica-Bold", leading=16,
                                            spaceAfter=8)))

    portfolio_impact = content.get("portfolio_impact", "")
    if portfolio_impact:
        story.append(Paragraph("PORTFOLIO IMPACT", h2))
        story.append(Paragraph(portfolio_impact, body))
        story.append(Spacer(1, 4 * mm))

    risk_alert = content.get("risk_alert")
    if risk_alert:
        alert_tbl = Table(
            [[Paragraph("⚠ RISK ALERT", s("RA", fontSize=9, textColor=DANGER,
                                           fontName="Helvetica-Bold")),
              Paragraph(risk_alert, s("RB", fontSize=9, textColor=BODY,
                                      fontName="Helvetica", leading=13))]],
            colWidths=[30 * mm, 144 * mm],
        )
        alert_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), HexColor("#FEF2F2")),
            ("LINEABOVE",     (0, 0), (-1, 0),  0.5, DANGER),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.5, DANGER),
            ("TOPPADDING",    (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(alert_tbl)
        story.append(Spacer(1, 6 * mm))

    week_ahead = content.get("week_ahead", "")
    if week_ahead:
        story.append(Paragraph("THE WEEK AHEAD", h2))
        story.append(Paragraph(week_ahead, body))

    story.append(PageBreak())

    # ── PAGE 3+: CURRENCY PAIR ANALYSIS ───────────────────────────────────────
    pairs = content.get("pair_commentary", [])
    if pairs:
        story.append(Paragraph("Currency Pair Analysis", h1))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GOLD, spaceAfter=6 * mm))

        for pc in pairs:
            pair       = pc.get("pair", "")
            movement   = pc.get("movement", "")
            client_imp = pc.get("client_impact", "")
            outlook    = pc.get("outlook", "")
            action     = pc.get("action")
            favourable = pc.get("favourable", True)

            # Movement colour
            move_color = SUCCESS if favourable else DANGER

            # Pair header row (NAVY background)
            hdr = Table(
                [[Paragraph(pair, pair_h),
                  Paragraph(movement, s("MV", fontSize=9, textColor=move_color,
                                         fontName="Helvetica-Bold", alignment=TA_RIGHT))]],
                colWidths=[130 * mm, 44 * mm],
            )
            hdr.setStyle(TableStyle([
                ("BACKGROUND",    (0, 0), (-1, -1), NAVY_LT),
                ("TOPPADDING",    (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("LEFTPADDING",   (0, 0), (-1, -1), 10),
                ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
                ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
            ]))

            # Content rows
            block = [hdr]
            if client_imp:
                block.append(Paragraph(client_imp, s("CI", fontSize=9, textColor=BODY,
                                                       fontName="Helvetica", leading=14,
                                                       spaceBefore=4, spaceAfter=2)))
            if outlook:
                block.append(Paragraph(outlook, s("OL", fontSize=8, textColor=GREY,
                                                    fontName="Helvetica", leading=12,
                                                    spaceAfter=2)))
            if action:
                action_tbl = Table(
                    [[Paragraph(f"Recommended action: {action}", action_s)]],
                    colWidths=[174 * mm],
                )
                action_tbl.setStyle(TableStyle([
                    ("BACKGROUND",    (0, 0), (-1, -1), HexColor("#FEF9EC")),
                    ("LINEBEFORE",    (0, 0), (0, -1),  3, GOLD),
                    ("TOPPADDING",    (0, 0), (-1, -1), 6),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                    ("LEFTPADDING",   (0, 0), (-1, -1), 10),
                ]))
                block.append(action_tbl)

            block.append(Spacer(1, 6 * mm))
            story.append(KeepTogether(block))

    # ── ECONOMIC CALENDAR ─────────────────────────────────────────────────────
    key_events = content.get("key_events", [])
    if key_events:
        story.append(Paragraph("Economic Calendar", h1))
        story.append(HRFlowable(width="100%", thickness=0.5, color=GOLD, spaceAfter=4 * mm))

        cal_data = [["DATE", "CCY", "EVENT", "IMPACT", "DESCRIPTION"]]
        for ev in key_events:
            ev_date    = ev.get("date", "")
            ccy        = ev.get("currency", "")
            event_name = ev.get("event", "")
            impact     = ev.get("impact", "")
            desc       = ev.get("description", "")

            # Format date nicely
            try:
                ev_date = date.fromisoformat(ev_date).strftime("%d %b")
            except Exception:
                pass

            impact_color = IMPACT_COLORS.get(impact, GREY)
            cal_data.append([
                Paragraph(ev_date,    s(f"ED{ccy}", fontSize=8, textColor=BODY,
                                         fontName="Helvetica-Bold")),
                Paragraph(ccy,        s(f"EC{ccy}", fontSize=8, textColor=BODY,
                                         fontName="Helvetica-Bold")),
                Paragraph(event_name, s(f"EN{ccy}", fontSize=8, textColor=BODY,
                                         fontName="Helvetica")),
                Paragraph(impact,     s(f"EI{ccy}", fontSize=8, textColor=impact_color,
                                         fontName="Helvetica-Bold")),
                Paragraph(desc,       s(f"DE{ccy}", fontSize=7, textColor=GREY,
                                         fontName="Helvetica", leading=11)),
            ])

        cal_tbl = Table(cal_data, colWidths=[18 * mm, 12 * mm, 42 * mm, 18 * mm, 84 * mm])
        cal_tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0),  NAVY),
            ("TEXTCOLOR",     (0, 0), (-1, 0),  white),
            ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, 0),  8),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [LIGHT, white]),
            ("GRID",          (0, 0), (-1, -1), 0.4, HexColor("#E5E7EB")),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 6),
            ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ]))
        story.append(cal_tbl)
        story.append(Spacer(1, 8 * mm))

    # ── DISCLAIMER ────────────────────────────────────────────────────────────
    story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#E5E7EB"),
                             spaceBefore=4 * mm, spaceAfter=4 * mm))
    story.append(Paragraph(DISCLAIMER_TEXT, small))

    # ── PAGE FOOTER (drawn on canvas — appears on every page) ────────────────
    def _footer(canvas, doc):
        canvas.saveState()
        canvas.setFont("Helvetica", 7)
        canvas.setFillColor(MUTED)
        canvas.drawString(
            18 * mm, 12 * mm,
            f"Generated by Sumnohow AI Engine  ·  {company_name}  ·  {date_display}"
        )
        canvas.drawRightString(
            A4[0] - 18 * mm, 12 * mm,
            f"Page {doc.page}"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=_footer, onLaterPages=_footer)
    buffer.seek(0)
    return buffer.read()
