"""
services/market_report_service.py

Generates personalised weekly FX market reports using Claude AI.
One report per company per week — stored in market_reports table.
Emails via Resend on the weekly cron run.
"""

import os
import json
import logging
import httpx
from datetime import date, timedelta

logger = logging.getLogger(__name__)

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY")
RESEND_API_KEY    = os.getenv("RESEND_API_KEY")
CLAUDE_MODEL      = "claude-sonnet-4-6"

DISCLAIMER = (
    "This report is generated by the Sumnohow AI engine for informational purposes only. "
    "It does not constitute financial advice or a recommendation to execute any transaction. "
    "All hedging decisions should be made in consultation with your treasury team and banking "
    "partners. Rates shown are indicative only."
)


# ── Main entry point ──────────────────────────────────────────────────────────

async def generate_market_report(company_id: int, db) -> dict:
    """
    1. Fetch company's active exposures + hedge coverage from DB
    2. Get current spot rates from in-memory cache
    3. Get 7-day historical rates from ECB
    4. Build personalised prompt
    5. Call Claude API
    6. Parse JSON response
    7. Store in market_reports table
    8. Return report dict
    """
    from sqlalchemy import text
    from database import get_rate
    from services.ecb_rates import get_ecb_close_rate

    # ── Company info ──────────────────────────────────────────────────────────
    company = db.execute(
        text("SELECT id, name, base_currency, alert_email FROM companies WHERE id = :cid AND (is_active IS NULL OR is_active = true)"),
        {"cid": company_id}
    ).fetchone()
    if not company:
        raise ValueError(f"Company {company_id} not found or inactive")

    company_name  = company._mapping["name"]
    base_currency = company._mapping["base_currency"] or "EUR"

    # ── Active exposures with hedge coverage ──────────────────────────────────
    rows = db.execute(text("""
        SELECT
            e.id, e.from_currency, e.to_currency, e.amount,
            e.budget_rate, e.description, e.end_date,
            COALESCE(SUM(
                CASE WHEN ht.status IN ('executed','confirmed') THEN ht.amount ELSE 0 END
            ), 0) AS hedged_amount
        FROM exposures e
        LEFT JOIN hedge_tranches ht ON ht.exposure_id = e.id
        WHERE e.company_id = :cid
          AND (e.is_active IS NULL OR e.is_active = true)
          AND (e.archived  IS NULL OR e.archived  = false)
        GROUP BY e.id, e.from_currency, e.to_currency, e.amount, e.budget_rate, e.description, e.end_date
        ORDER BY e.amount DESC
    """), {"cid": company_id}).fetchall()

    if not rows:
        raise ValueError(f"No active exposures found for company {company_id}")

    today    = date.today()
    week_ago = today - timedelta(days=7)

    exposure_data = []
    for row in rows:
        e = row._mapping
        from_ccy = e["from_currency"]
        to_ccy   = e["to_currency"]

        # Current spot from in-memory cache (fast)
        try:
            current_spot = get_rate(from_ccy, to_ccy)
        except Exception:
            current_spot = None

        # 7-day historical rates from ECB
        # ECB series returns {CCY}/EUR (units of CCY per 1 EUR).
        # Cross rate: from_ccy/to_ccy = to_eur_units / from_eur_units
        # e.g. GBP/NOK = NOK_per_EUR / GBP_per_EUR = 11.7 / 0.86 ≈ 13.6
        try:
            from_eur_today = 1.0 if from_ccy == "EUR" else await get_ecb_close_rate(from_ccy, today)
            from_eur_week  = 1.0 if from_ccy == "EUR" else await get_ecb_close_rate(from_ccy, week_ago)
            to_eur_today   = 1.0 if to_ccy   == "EUR" else await get_ecb_close_rate(to_ccy,   today)
            to_eur_week    = 1.0 if to_ccy   == "EUR" else await get_ecb_close_rate(to_ccy,   week_ago)

            spot_today = (to_eur_today / from_eur_today) if from_eur_today > 0 else None
            spot_week  = (to_eur_week  / from_eur_week)  if from_eur_week  > 0 else None
        except Exception as ecb_err:
            logger.warning(f"ECB lookup failed for {from_ccy}/{to_ccy}: {ecb_err}")
            spot_today = current_spot
            spot_week  = None

        # Fall back to live cache if ECB didn't return data
        if spot_today is None:
            spot_today = current_spot

        # Week-on-week rate change
        rate_change_pct = None
        if spot_today and spot_week and spot_week > 0:
            rate_change_pct = (spot_today - spot_week) / spot_week * 100

        # Floating P&L in base currency
        total_amount  = float(e["amount"] or 0)
        hedged_amount = float(e["hedged_amount"] or 0)
        open_amount   = max(total_amount - hedged_amount, 0)
        budget_rate   = float(e["budget_rate"] or 0)
        hedge_pct     = (hedged_amount / total_amount * 100) if total_amount > 0 else 0

        floating_pnl_base = None
        if spot_today and budget_rate and open_amount > 0:
            raw_pnl = (spot_today - budget_rate) * open_amount  # in to_ccy
            try:
                if to_ccy == base_currency:
                    floating_pnl_base = raw_pnl
                else:
                    from_base_rate = get_rate(from_ccy, base_currency)
                    if spot_today > 0:
                        floating_pnl_base = raw_pnl * (from_base_rate / spot_today)
                    else:
                        floating_pnl_base = raw_pnl
            except Exception:
                floating_pnl_base = raw_pnl

        exposure_data.append({
            "pair":                 f"{from_ccy}/{to_ccy}",
            "from_currency":        from_ccy,
            "to_currency":          to_ccy,
            "notional":             total_amount,
            "hedged_pct":           round(hedge_pct, 1),
            "budget_rate":          budget_rate,
            "current_spot":         round(spot_today, 6) if spot_today else None,
            "rate_7d_ago":          round(spot_week,  6) if spot_week  else None,
            "rate_change_pct":      round(rate_change_pct, 3) if rate_change_pct is not None else None,
            "floating_pnl_base":    round(floating_pnl_base, 0) if floating_pnl_base is not None else None,
            "description":          e.get("description") or "",
        })

    # ── Build prompt context ──────────────────────────────────────────────────
    exposure_summary = "\n".join([
        f"- {ed['pair']}: {ed['notional']:,.0f} {ed['from_currency']} notional, "
        f"{ed['hedged_pct']}% hedged, budget rate {ed['budget_rate']}, "
        f"current spot {ed['current_spot'] or 'N/A'}"
        for ed in exposure_data
    ])

    rate_movements = "\n".join([
        f"- {ed['pair']}: "
        + (
            f"{'+' if (ed['rate_change_pct'] or 0) >= 0 else ''}{ed['rate_change_pct']:.2f}% "
            f"(spot {ed['current_spot']}, was {ed['rate_7d_ago']} a week ago)"
            if ed["rate_change_pct"] is not None
            else f"spot {ed['current_spot'] or 'N/A'} (no 7-day history available)"
        )
        for ed in exposure_data
    ])

    valid_pnl = [ed for ed in exposure_data if ed["floating_pnl_base"] is not None]
    total_pnl = sum(ed["floating_pnl_base"] for ed in valid_pnl)
    pnl_summary = (
        f"Total floating P&L vs budget: {base_currency} {total_pnl:+,.0f}\n"
        + "\n".join([
            f"- {ed['pair']}: {base_currency} {ed['floating_pnl_base']:+,.0f} floating P&L"
            for ed in valid_pnl
        ])
    )

    # ── Call Claude ───────────────────────────────────────────────────────────
    system_prompt = (
        "You are a senior FX market analyst writing a personalised weekly currency report "
        "for a corporate treasury client. You write in a professional but accessible tone — "
        "suitable for a CFO, not a trader. Be specific, be direct, reference their actual "
        "numbers. Never use generic filler. Every sentence must be relevant to this specific client."
    )

    user_prompt = f"""Write a weekly FX market report for {company_name}.

Their active currency exposures this week:
{exposure_summary}

Key rate movements this week:
{rate_movements}

Portfolio P&L summary:
{pnl_summary}

Structure the report as JSON with these exact sections:
{{
  "headline": "One sentence summary of the week",
  "portfolio_impact": "2-3 sentences on overall P&L impact",
  "pair_commentary": [
    {{
      "pair": "GBP/NOK",
      "movement": "+1.2% this week",
      "client_impact": "Your GBP 8M exposure moved...",
      "outlook": "Key levels to watch...",
      "action": "Consider..." or null
    }}
  ],
  "week_ahead": "2-3 sentences on key events/risks next week",
  "risk_alert": "Any urgent items requiring attention" or null
}}

Only include pairs the client actually holds. Return ONLY valid JSON. No markdown, no preamble."""

    report_content = await _call_claude(system_prompt, user_prompt)

    # ── Store in DB ───────────────────────────────────────────────────────────
    result_row = db.execute(text("""
        INSERT INTO market_reports (company_id, report_date, report_type, content_json, generated_at)
        VALUES (:cid, :rdate, 'weekly', :content, NOW())
        RETURNING id, generated_at
    """), {
        "cid":     company_id,
        "rdate":   today.isoformat(),
        "content": json.dumps(report_content),
    }).fetchone()
    db.commit()

    return {
        "id":           result_row._mapping["id"],
        "company_id":   company_id,
        "company_name": company_name,
        "report_date":  today.isoformat(),
        "generated_at": result_row._mapping["generated_at"].isoformat(),
        "content":      report_content,
    }


# ── Claude API call ───────────────────────────────────────────────────────────

async def _call_claude(system_prompt: str, user_prompt: str) -> dict:
    """POST to Anthropic Messages API and return parsed JSON."""
    if not ANTHROPIC_API_KEY:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set")

    payload = {
        "model":      CLAUDE_MODEL,
        "max_tokens": 2048,
        "system":     system_prompt,
        "messages":   [{"role": "user", "content": user_prompt}],
    }

    async with httpx.AsyncClient(timeout=90) as client:
        resp = await client.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key":           ANTHROPIC_API_KEY,
                "anthropic-version":   "2023-06-01",
                "content-type":        "application/json",
            },
            json=payload,
        )

    if resp.status_code != 200:
        raise RuntimeError(f"Claude API error {resp.status_code}: {resp.text[:400]}")

    raw = resp.json()["content"][0]["text"].strip()

    # Strip markdown code fences if Claude wrapped the JSON
    if raw.startswith("```"):
        lines = raw.splitlines()
        raw = "\n".join(
            line for line in lines
            if not (line.strip().startswith("```") or line.strip() == "json")
        )

    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        logger.error(f"Claude returned invalid JSON: {e}\nRaw (first 500 chars): {raw[:500]}")
        raise ValueError(f"Claude returned invalid JSON: {e}")


# ── Email delivery ─────────────────────────────────────────────────────────────

async def send_market_report_email(report: dict, to_email: str, company_name: str) -> bool:
    """Send weekly market report email via Resend. Returns True if sent."""
    if not RESEND_API_KEY:
        logger.warning("RESEND_API_KEY not set — skipping market report email")
        return False

    content = report.get("content", {})
    report_date = report.get("report_date", "")
    headline    = content.get("headline", "Your Weekly FX Market Report")
    portfolio_impact = content.get("portfolio_impact", "")
    week_ahead  = content.get("week_ahead", "")
    risk_alert  = content.get("risk_alert")
    pairs_commentary = content.get("pair_commentary", [])

    NAVY = "#1A2744"
    GOLD = "#C9A86C"
    DANGER = "#EF4444"

    # ── Pair commentary rows ──────────────────────────────────────────────────
    pair_rows_html = ""
    for pc in pairs_commentary:
        pair     = pc.get("pair", "")
        movement = pc.get("movement", "")
        impact   = pc.get("client_impact", "")
        outlook  = pc.get("outlook", "")
        action   = pc.get("action")

        action_html = ""
        if action:
            action_html = f"""
            <div style="margin-top:8px;padding:8px 12px;background:rgba(201,168,108,0.1);
                        border-left:3px solid {GOLD};border-radius:4px;
                        font-size:13px;color:#92711A;">
              <strong>Action:</strong> {action}
            </div>"""

        pair_rows_html += f"""
        <div style="margin-bottom:20px;padding:16px;background:#F9FAFB;border-radius:8px;
                    border:1px solid #E5E7EB;">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8px;">
            <strong style="font-size:15px;color:{NAVY};">{pair}</strong>
            <span style="font-size:13px;font-weight:600;color:{'#10B981' if '+' in movement else DANGER};">
              {movement}
            </span>
          </div>
          <p style="margin:4px 0;font-size:13px;color:#374151;">{impact}</p>
          <p style="margin:4px 0;font-size:12px;color:#6B7280;">{outlook}</p>
          {action_html}
        </div>"""

    # ── Risk alert banner ─────────────────────────────────────────────────────
    alert_html = ""
    if risk_alert:
        alert_html = f"""
        <div style="margin:20px 0;padding:14px 18px;background:rgba(239,68,68,0.08);
                    border:1px solid rgba(239,68,68,0.4);border-radius:8px;">
          <strong style="color:{DANGER};">⚠ Risk Alert</strong>
          <p style="margin:6px 0 0;font-size:13px;color:#374151;">{risk_alert}</p>
        </div>"""

    html = f"""
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;
                max-width:620px;margin:0 auto;background:#ffffff;">

      <!-- Header -->
      <div style="background:{NAVY};padding:28px 32px;border-radius:8px 8px 0 0;">
        <p style="color:{GOLD};font-size:10px;letter-spacing:3px;text-transform:uppercase;
                  margin:0 0 6px;">SUMNOHOW</p>
        <h1 style="color:white;font-size:20px;font-weight:700;margin:0;">Weekly FX Report</h1>
        <p style="color:#8DA4C4;font-size:13px;margin:4px 0 0;">{company_name} · {report_date}</p>
      </div>

      <!-- Headline -->
      <div style="padding:24px 32px;background:#FAFBFC;border-bottom:1px solid #E5E7EB;">
        <p style="font-size:17px;font-weight:600;color:{NAVY};margin:0;line-height:1.4;">
          {headline}
        </p>
      </div>

      <div style="padding:24px 32px;">

        <!-- Portfolio Impact -->
        <h2 style="font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;
                   color:{GOLD};margin:0 0 10px;">Portfolio Impact</h2>
        <p style="font-size:14px;color:#374151;line-height:1.6;margin:0 0 24px;">
          {portfolio_impact}
        </p>

        <!-- Risk alert if present -->
        {alert_html}

        <!-- Per-pair commentary -->
        <h2 style="font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;
                   color:{GOLD};margin:0 0 12px;">Your Currency Pairs This Week</h2>
        {pair_rows_html}

        <!-- Week ahead -->
        <h2 style="font-size:11px;font-weight:700;letter-spacing:1.5px;text-transform:uppercase;
                   color:{GOLD};margin:24px 0 10px;">The Week Ahead</h2>
        <p style="font-size:14px;color:#374151;line-height:1.6;margin:0 0 24px;">
          {week_ahead}
        </p>

        <!-- CTA -->
        <div style="text-align:center;margin:28px 0;">
          <a href="https://app.sumnohow.com/reports"
             style="display:inline-block;background:{NAVY};color:white;padding:12px 28px;
                    border-radius:8px;font-size:14px;font-weight:600;text-decoration:none;">
            View Full Report in Dashboard →
          </a>
        </div>

      </div>

      <!-- Disclaimer + footer -->
      <div style="padding:20px 32px;background:#F4F6FA;border-top:1px solid #E5E7EB;
                  border-radius:0 0 8px 8px;">
        <p style="font-size:11px;color:#9CA3AF;line-height:1.5;margin:0 0 8px;">
          {DISCLAIMER}
        </p>
        <p style="font-size:11px;color:#9CA3AF;margin:0;">
          Sumnohow FX Risk Management · To update your preferences, visit Settings in your dashboard.
        </p>
      </div>

    </div>"""

    subject = f"📊 Your Weekly FX Report — {company_name} — {report_date}"

    try:
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(
                "https://api.resend.com/emails",
                headers={
                    "Authorization":  f"Bearer {RESEND_API_KEY}",
                    "Content-Type":   "application/json",
                },
                json={
                    "from":    "Sumnohow <alerts@updates.sumnohow.com>",
                    "to":      [to_email],
                    "subject": subject,
                    "html":    html,
                },
            )
        if resp.status_code == 200:
            logger.info(f"Market report email sent to {to_email} for {company_name}")
            return True
        else:
            logger.error(f"Resend error {resp.status_code} for {to_email}: {resp.text[:200]}")
            return False
    except Exception as e:
        logger.error(f"Failed to send market report email to {to_email}: {e}")
        return False
